# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-23 08:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(max_length=1000, upload_to='profilePictures')),
                ('artistic_name', models.CharField(max_length=255)),
                ('account_number', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('telephone', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contentUrl', models.FileField(blank=True, max_length=1000, null=True, upload_to='audios')),
                ('ratingCount', models.IntegerField()),
                ('likesCount', models.IntegerField()),
                ('dislikesCount', models.IntegerField()),
                ('playsCount', models.IntegerField()),
                ('averageRating', models.IntegerField()),
                ('length', models.IntegerField()),
                ('cover', models.ImageField(max_length=1000, null=True, upload_to='covers')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2016, 11, 23, 8, 9, 43, 232740, tzinfo=utc), editable=False)),
                ('artwork_type', models.CharField(choices=[('ALB', 'Album'), ('SNG', 'Cancion'), ('SND', 'Sonido')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comercial_agent.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(max_length=1000, upload_to='profilePictures')),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('telephone', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(max_length=1000, upload_to='profilePictures')),
                ('telephone', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('initial_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('description', models.CharField(max_length=5000)),
                ('notification_type', models.CharField(choices=[('PR', 'Privada'), ('PB', 'Publica')], default='PB', max_length=2)),
                ('notification_state', models.CharField(choices=[('CRE', 'Creada'), ('PUB', 'Publicada'), ('CER', 'Cerrada'), ('FIN', 'Finalizada')], default='CRE', max_length=3)),
                ('business_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial_agent.BusinessAgent')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PostulatedArtwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tied', models.BooleanField(default=False)),
                ('is_winner', models.BooleanField(default=False)),
                ('polls_num', models.IntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial_agent.Artist')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial_agent.Notification')),
            ],
        ),
        migrations.CreateModel(
            name='RequestedPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('features', models.CharField(max_length=1020)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial_agent.Notification')),
            ],
        ),
        migrations.CreateModel(
            name='SoundType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comercial_agent.Artwork')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial_agent.Genre')),
            ],
            bases=('comercial_agent.artwork',),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comercial_agent.Artwork')),
                ('song_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial_agent.Album')),
            ],
            bases=('comercial_agent.artwork',),
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comercial_agent.Artwork')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial_agent.SoundType')),
            ],
            bases=('comercial_agent.artwork',),
        ),
        migrations.AddField(
            model_name='tag',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial_agent.Artwork'),
        ),
        migrations.AddField(
            model_name='postulatedartwork',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial_agent.Artwork'),
        ),
        migrations.AddField(
            model_name='postulatedartwork',
            name='postulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial_agent.Postulation'),
        ),
        migrations.AddField(
            model_name='postulatedartwork',
            name='requestedPiece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial_agent.RequestedPiece'),
        ),
        migrations.AddField(
            model_name='poll',
            name='postulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial_agent.Postulation'),
        ),
        migrations.AddField(
            model_name='poll',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artwork',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial_agent.ArtworkCollection'),
        ),
    ]
