# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-10-02 02:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comercial_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 2, 2, 7, 32, 825638, tzinfo=utc), editable=False),
        ),
    ]
